name: beer_app
description: BeerApp

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^9.2.2
  collection: ^1.18.0

  get_it: ^7.7.0
  injectable: ^2.4.4
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  flutter_hooks: ^0.20.5
  hooked_bloc: ^1.5.0

  dio: ^5.7.0
  retrofit: ^4.4.1
  cached_network_image: ^3.4.1

  equatable: ^2.0.5
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  talker: ^4.4.1
  talker_dio_logger: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  strict: ^2.1.0
  build_runner: ^2.4.13

  auto_route_generator: ^9.0.0
  retrofit_generator: ^9.1.2
  injectable_generator: ^2.6.2

  json_serializable: ^6.8.0
  freezed: ^2.5.7

  bloc_test: ^9.1.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true
